name: Build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Build solution
        run: msbuild PhysicsGame.sln /p:Configuration=Release

      - name: Create artifact directory
        run: mkdir artifact/PhysicsGame

      - name: Dir
        run: dir

      - name: Copy all executables to artifact directory
        run: |
          mkdir artifact\PhysicsGame
          Get-ChildItem -Path . -Recurse -Filter *.exe | Copy-Item -Destination artifact\PhysicsGame

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PhysicsGame
          path: artifact/PhysicsGame/
