name: Build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Build solution
        run: msbuild PhysicsGame.sln /p:Configuration=Release

      - name: Create artifact directory
        run: mkdir artifact/PhysicsGame

      - name: Dir
        run: dir

      - name: Copy the executable to the artifact directory
        run: copy .\PhysicsGame\bin\Release\*.exe artifact\PhysicsGame\

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PhysicsGame
          path: artifact/PhysicsGame/
